### ISSUE TITLE
Import NcML service metadata to SOLR table

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/pavics-vdb#2]
More or less linked to this in https://github.com/Ouranosinc/PAVICS-DataCatalog/issues/52.  But looking specifically at importing to the SOLR database:
example NcML service:

https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/ncml/birdhouse/nrcan/nrcan_canada_daily/tasmin/nrcan_canada_daily_tasmin_2012.nc?catalog=https%3A%2F%2Fpavics.ouranos.ca%2Ftwitcher%2Fows%2Fproxy%2Fthredds%2Fcatalog%2Fbirdhouse%2Fnrcan%2Fnrcan_canada_daily%2Ftasmin%2Fcatalog.html&dataset=birdhouse%2Fnrcan%2Fnrcan_canada_daily%2Ftasmin%2Fnrcan_canada_daily_tasmin_2012.nc

**Comment by huard** [comment]
Not using SOLR anymore.
