### ISSUE TITLE
Optimize climex ncml 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-vdb#43]
The climex ncml end point is really slow to respond. I suspect it can be optimized. 

See for example https://ferret.pmel.noaa.gov/LAS/documentation/installer-documentation/adding-ensemble-data/creating-an-ensemble-aggregation where the time aggregation is done for each ensemble member, then another ncml joins the individual members. 

Also, instead of having to read each file to extract the time, maybe we can define it within the ncml itself.

**Comment by tlogan2000** [comment]
@huardcan we close this issue? move to ssd drives has allowed much better perf
