### ISSUE TITLE
Metadata attribute errors

### ISSUE THREAD

**Issue by huard** [Ouranosinc/pavics-vdb#45]
Found some errors in the NcML while implementing metadata validation.

- day_NorESM1-ME_historical+rcp85_r1i1p1_19500101-21001231_bccaqv2.ncml
  - [x] missing driving_institution, driving_institute_id
- day_NorESM1-ME_historical+rcp45_r1i1p1_19500101-21001231_bccaqv2.ncml
  - [x] missing driving_institution, driving_institute_id
- day_NorESM1-ME_historical+rcp26_r1i1p1_19500101-21001231_bccaqv2.ncml
  - [x] missing driving_institution, driving_institute_id
- day_*_nex-gddp.ncml (won't fix, will remove)
  - [x] `bounds` target variable (time_bnds) does not exist (not critical)
  - [x]  missing driving_model, driving_institution, driving_institute_id
- bccaqv2_climindices_ensemble_percentiles_*.ncml
  - [x]  missing driving_model, driving_institute_id
  - [x] frequency is empty (' ')
- Decadal_CMIP5_ensemble-percentiles_allrcps_2006-2100_slr_YS.ncml
  - [x] missing driving_model, frequency, target_dataset, driving_institution, driving_institute_id
- anusplin_v1_climindices_gridded_observations_*.ncml
  - [x] missing version
 - day_climex-crcm5_historical+rcp85.ncml
   - [x] variable rotated_pole has no long_name
 - ECCC_AHCCD_gen3_temperature.ncml
   - [x] Variables `no` and `joined` have no long_name.

**Comment by huard** [comment]
Other questions: 
- Some catalogs use `activity`, others `project_id`. Should we all move to `activity` ?

**Comment by huard** [comment]
- [ ] GEPS forecast `pr` has no `standard_name`, but maybe this is ok since it's water accumulation.

**Comment by tlogan2000** [comment]
> Other questions:
> 
>     * Some catalogs use `activity`, others `project_id`. Should we all move to `activity` ?

Yes for me.  For the internal data we are trying to follow CMIP6 style CVs as much as possible

**Comment by huard** [comment]
In cmip5, THREDDS does not recognize the `realization` variable as a coordinate (no `<ncml:attribute name="_CoordinateAxisType" value="Realization" />` attribute).

**Comment by huard** [comment]
Is `dataset_id` the same thing as activity?

**Comment by tlogan2000** [comment]
Not necessarily in my mind, especially for bias-adjusted data...  e.g. `activity=CMIP5` for multiple bias-adjusted `dataset_ids` ...

**Comment by huard** [comment]
For error handling, we have two kinds of errors: 
- Data is present but does not comply with CV
- Data is missing

Our options are: 
- Raise an error, entire catalog is not created. 
- Logs a warning, entry is skipped from catalog. 
- Define fields as optional, so when a value is wrong or missing, we set it to None and create entry anyway. 

The deployed version sets missing values to NA and logs nothing. 
I can set things up super strict, so that only fully-compliant entries make their way into the catalog, and a log is created of the remaining errors.

**Comment by tlogan2000** [comment]
@huard for many of these there is no real value that makes sense.  
E.g. `driving model` etc for ensemble stats.   

of 
Station obs that have numerous variables such as `province`,  `station_name`  with no units.  

I can try to patch these with attr values "None" or some equivalent?

**Comment by huard** [comment]
In climex, `rotated_pole` should be a dimensionless char, eg.
```
     char rotated_pole;
       :grid_mapping_name = "rotated_latitude_longitude";
       :grid_north_pole_latitude = "37.5";
       :grid_north_pole_longitude = "177.5";
```
At the moment it is a string over the time dimension.

**Comment by tlogan2000** [comment]
@huard for `bccaqv2_climindices_ensemble_percentiles_*.ncml` entry:

- driving_model, institution no longer relevant as they are multi-model ensemble statistics
- Frequency is somewhat problematic (except annual) as data is split into separate dataset for each month / season?  E.g.  ensemble stats for month of jan for every year would be yearly freq?   Probably why I left blank...

**Comment by tlogan2000** [comment]
For `climex` I can easily remove the existing `rotated_pole` variable by adding a `<remove name="rotated_pole" type="variable" />`  but not sure how to add in the new info in your example above? Have you seen an example of adding a variable to an ncml that is not in a netcdf file?  

Worst case I could add the info to the global attrs?  Not sure why this is a variable in the first place.  Opinion

**Comment by huard** [comment]
RE Climex, I *think* you can just do something like 
```
  <variable name="rotated_pole" shape="" type="char">
    <attribute name="grid_mapping_name" type="String" value="rotated_latitude_longitude" />
  </variable>
```

RE BCCAQV2, maybe then this should go into another collection entirely, or we decide on a special keyword that indicates it's a multi-model product.

**Comment by tlogan2000** [comment]
I still feel that the BCCAQv2 data is `bias_adjusted` ... what if the attribute entries for `driving_model` and `institution` both simply indicate soemthing along the lines of  `model-model statistics`?

**Comment by tlogan2000** [comment]
Will give the CLImex suggestion a try

**Comment by huard** [comment]
Sounds good, let's try that.

**Comment by tlogan2000** [comment]
A bit convoluted but can clean up CLIMEX this way... I guess the various args in the ncml are not treated sequentially?  Anyways I have to rename the old `rotated_pole` to something else otherwise `remove` clears both 
```
<variable name="remove_var" orgName="rotated_pole" />
<remove name="remove_var" type="variable" />
<variable name="rotated_pole" shape="" type="char">
   <attribute name="grid_mapping_name" type="String" value="rotated_latitude_longitude" />
</variable>

```

**Comment by huard** [comment]
Smart !

**Comment by tlogan2000** [comment]
@huard I think https://github.com/Ouranosinc/pavics-vdb/pull/61 will have fixed all issues ... can you confirm that the catalogue builds successfully?

**Comment by huard** [comment]
Negative. In bias_adjusted/cmip5/
- pcic has `driving_institute_id` and `driving_model_id`, 
- climatedata_ca has `driving_institution` and no `driving_model_id`.
